#!/bin/zsh

function help () {
    echo "setup_shell - A simple script to help set up the environment for flask"
    echo "Meant to be called in the current shell environment (zsh), use source or . (dot) to do so"
    echo "eg:    . ./setup_shell <cmd>"
    echo "        source ./setup_shell <cmd> "
    echo ""
    echo "    setup_shell init  - creates venv + imports packages";
    echo "    setup_shell load  - loads venv + imports packages";
    echo "    setup_shell remove  - unload and destroy venv";
    echo "    setup_shell unload  -  unload venv";
}

function get_modules(){
    python -m pip install Flask==0.12.2
    python -m pip install Flask-WTF==0.14.2            # Form Creation/Handling
    python -m pip install Flask-SQLAlchemy==2.3.2  # SQL, SQLite, and Postgre support
    python -m pip install Flask-Migrate==2.1.1         # Database migration support
    python -m pip install Flask-Login==0.4.1            # For login persistance
}

function load_evn(){

   case "$(uname -s)" in

      Darwin)
        source venv/bin/activate
        export FLASK_APP=blog.py
        export FLASK_DEBUG=1
        echo 'Loaded Virtual Environment'
        ;;

      Linux)
        source venv/bin/activate
        export FLASK_APP=blog.py
        export FLASK_DEBUG=1
        echo 'Loaded Virtual Environment'
        ;;

      CYGWIN*|MINGW32*|MSYS*|MINGW64*)
        source venv/Scripts/activate
        set FLASK_APP=blog.py
        set FLASK_DEBUG=1
        echo 'Loaded Virtual Environment'
        ;;

      *)
        echo 'other OS - Unable to Set up environment' 
        ;;
   esac
}

# Main Args Parser

if [ $1 ]
then
    case "$1" in
    init)
      echo "Attempting to install python virtual environment"
      case "$(uname -s)" in

         Darwin)
           echo 'Mac OS X'
           ;;

         Linux)
           echo 'Linux'
           sudo apt-get install python3-venv
           python3.6 -m venv venv
           ;;

         CYGWIN*|MINGW32*|MSYS*|MINGW64*)
           echo 'MS Windows - ensure that Python 3.6 is already installed'
           python -m venv venv
           ;;

         *)
           echo 'other OS - Please Manually install venv' 
           ;;
      esac

      load_evn;
      get_modules;
      ;;

    load)
      load_evn;
      ;;

    remove)
      deactivate
      rm -rf venv
      ;;

    unload)
      deactivate
      ;;

    *)
        help;
    ;;
    esac
else
    help;
fi
